### ISSUE TITLE
Actual crashes logged by Google Play

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/microMathematics#35]
- java.lang.RuntimeException: Canvas: trying to draw too large(109906512bytes) bitmap.
    at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:260)
    at android.graphics.Canvas.drawBitmap(Canvas.java:1336)
    at com.mkulesh.micromath.plots.views.SurfacePlotView.onDraw(SurfacePlotView.java:320)
    at android.view.View.draw(View.java:17071)
    at android.view.View.updateDisplayListIfDirty(View.java:16053)
    at android.view.View.draw(View.java:16837)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.draw(View.java:17074)
    at android.view.View.updateDisplayListIfDirty(View.java:16053)
    at android.view.View.draw(View.java:16837)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.draw(View.java:17074)
    at android.view.View.updateDisplayListIfDirty(View.java:16053)
    at android.view.View.draw(View.java:16837)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.draw(View.java:17074)
    at android.view.View.updateDisplayListIfDirty(View.java:16053)
    at android.view.View.draw(View.java:16837)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.draw(View.java:17074)
    at android.view.View.updateDisplayListIfDirty(View.java:16053)
    at android.view.View.draw(View.java:16837)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.draw(View.java:17074)
    at com.mkulesh.micromath.widgets.TwoDScrollView.draw(TwoDScrollView.java:190)

**Comment by Symbian9** [comment]
* https://ru.stackoverflow.com/questions/497105/Ошибка-java-lang-arrayindexoutofboundsexception
* https://stackoverflow.com/questions/5554734/what-causes-a-java-lang-arrayindexoutofboundsexception-and-how-do-i-prevent-it
* https://stackoverflow.com/questions/32568261/how-to-avoid-arrayindexoutofboundsexception-or-indexoutofboundsexception
* http://javarevisited.blogspot.in/2016/02/solving-javalangarrayindexoutofboundsexception-0-1-2-in-java.html
* https://github.com/EsotericSoftware/kryo/issues/448

**Comment by mkulesh** [comment]
Fixed in v2.15.5
